### ISSUE TITLE
Use in real robot

### ISSUE THREAD

**Issue by stardobas** [merose/diff_drive_controller#14]
Need help for use in real robot; this work is amazing; I have a lot of difficult; my rover is rover5 and use ros-motor-romeo-quad; but your mock_robot is complete perfect rover... How I can use my rover?

**Comment by stardobas** [comment]
a little update; my nodes just provide lwheel_ticks and rwheel_ticks ; i can control rover publishing in /command topic an int32multiarray like [30000,-30000,30000,-30000]  single number correspond to single motor , negative value = backward, positive value = forward (value between 10000 and - 10000 don't move the robot for too low power motor); If i run my node I see robot moving on Rviz when manually move the wheel or when control it.... but in your package is Mock_robot that use desired rate to generate wheel_thick; I need to understand your desired rate topic for generate a node rwheel_desired_rate and lwheel_desired_rate (I need to convert it to make usable for my rover)... I can receive 10 hz update cumulative ticks for wheel and can send unly 1 hz to control command for rover...

**Comment by merose** [comment]
You'll need to have a ROS node that subscribes to /cmd_vel and changes that into motor commands for the rover. For my small robots I use the ros_arduino_bridge node to send motor commands to an Arduino-like microcontroller that commands the motors. You can see an example of taking the /cmd_vel values and converting them to motor speeds in that package, lines 223–243 in this file: https://github.com/merose/ros_arduino_bridge/blob/indigo-devel/ros_arduino_python/src/ros_arduino_python/base_controller.py

If you already have a way of receiving motor commands, then you might take that example in ros_arduino_bridge and wrap in in a new Python node. Let me know if this makes sense.

**Comment by stardobas** [comment]
very good starting point... you use arduino and your is a beautifull python script... 
You are right.... but your nodes just do that... 
maybe I need a closed loop control to get my wheel speed and make same as wheel required speed...
Thank you very mutch

**Comment by merose** [comment]
Yes, it's a lot better if you have closed-loop control over the motors, but not absolutely essential. It's best if the motors have quadrature encoders. I have a PID control loop in my low-level control to command the motors. If you do not have encoders, you can do it open-loop by manually calibrating the motor commands to approximate motor speeds, but that has limitations: it won't work properly if you are on a slope, or crossing varied terrain, and it will drift as your battery voltage changes as the batteries drain. But if you do not have encoders you can still use that open-loop control and probably get adequate results, if you don't care how accurately your navigation plan is executed. That will work better if you are replanning often, too, so that you can actively adjust for poor motion control.

I'm going to close this issue, for now. Let me know if you have further questions.
